<?php

namespace ContainerJx0ZUbu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6eEz9_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M6eEz9.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M6eEz9.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'measurement' => ['privates', '.errored..service_locator.M6eEz9..App\\Entity\\Measurement', NULL, 'Cannot autowire service ".service_locator.M6eEz9.": it needs an instance of "App\\Entity\\Measurement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'measurement' => 'App\\Entity\\Measurement',
        ]);
    }
}
