<?php

namespace ContainerJx0ZUbu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeasurement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M6eEz9..App\Entity\Measurement' shared service.
     *
     * @return \App\Entity\Measurement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M6eEz9.": it needs an instance of "App\\Entity\\Measurement" but this type has been excluded in "config/services.yaml".');
    }
}
