controllers:
    resource:
        path: '../src/Controller/'
        namespace: 'App\Controller'
    type: 'attribute'

app_measurement_index:
    path: '/measurement'
    controller: 'App\Controller\MeasurementController::index'
    methods: ['GET']

when@prod:
    framework:
        router:
            strict_requirements: null
